name: sst_body_analysis

channels:
        - conda-forge

dependencies:
        - python=3.9.*
        - pip=20.*
        - numpy
        - pdal
        - rasterio

        - pip:
                - matplotlib
                - pandas
                - jinja2
                - tqdm
                - scipy
                - scikit_learn
                - seaborn
                - ptitprince
